drop table if exists ATTRIBUTE;
drop table if exists CHARACTER;
drop table if exists CHARACTER_EQUIPS_EQUIPMENT;
drop table if exists CHARACTER_HAS_ATTRIBUTE;
drop table if exists CHARACTER_HAS_ITEM;
drop table if exists CHAR_EQUIPS_DIE_IN_DICE_SET;
drop table if exists CLIMATE;
drop table if exists CLIMATE_MODIFIES_ATTRIBUTE;
drop table if exists CRAFTING_RECIPE;
drop table if exists CRAFTING_REQUIRES_RESSOURCE;
drop table if exists DICE_SET;
drop table if exists DIE;
drop table if exists DIE_TYPE;
drop table if exists EQUIPMENT_MODIFIES_ATTRIBUTE;
drop table if exists MONSTER;
drop table if exists MONSTER_CAN_DROP_ITEM;
drop table if exists PLAYER;
drop table if exists PLAYER_FINISH_QUEST;
drop table if exists QUEST;
drop table if exists QUEST_MADE_OF_ROOM;
drop table if exists QUEST_REWARDS_ITEM;
drop table if exists RESSOURCE;
drop table if exists ROOM;
drop table if exists ROOM_CONTAINS_MONSTER;

CREATE TABLE ATTRIBUTE (
    IdAttribute int NOT NULL,
    Name varchar(50)
  );
ALTER TABLE ATTRIBUTE ADD CONSTRAINT ATTRIBUTE_PK PRIMARY KEY ( IdAttribute );

CREATE TABLE CHARACTER (
    IdCharacter int NOT NULL
  );
ALTER TABLE CHARACTER ADD CONSTRAINT CHARACTER_PK PRIMARY KEY ( IdCharacter );

CREATE TABLE CHARACTER_EQUIPS_EQUIPMENT (
    IdCharacter int NOT NULL,
    IdEquipment int NOT NULL
  );
ALTER TABLE CHARACTER_EQUIPS_EQUIPMENT ADD CONSTRAINT CHARACTER_EQUIPS_EQUIPMENT_PK PRIMARY KEY ( IdCharacter, IdEquipment );

CREATE TABLE CHARACTER_HAS_ATTRIBUTE (
    IdCharacter int NOT NULL,
    IdAttribute int NOT NULL,
    Value int
  );
ALTER TABLE CHARACTER_HAS_ATTRIBUTE ADD CONSTRAINT CHARACTER_HAS_ATTRIBUTE_PK PRIMARY KEY ( IdCharacter, IdAttribute );

CREATE TABLE CHARACTER_HAS_ITEM (
    IdCharacter int NOT NULL,
    IdItem int NOT NULL,
    Count tinyint
  );
ALTER TABLE CHARACTER_HAS_ITEM ADD CONSTRAINT CHARACTER_HAS_ITEM_PK PRIMARY KEY ( IdCharacter, IdItem );

CREATE TABLE CHAR_EQUIPS_DIE_IN_DICE_SET (
    IdCharacter int NOT NULL,
    IdDie int NOT NULL,
    IdDiceSet int NOT NULL
  );
ALTER TABLE CHAR_EQUIPS_DIE_IN_DICE_SET ADD CONSTRAINT CHAR_EQUIPS_DIE_IN_DICE_SET_PK PRIMARY KEY ( IdCharacter, IdDie, IdDiceSet );

CREATE TABLE CLIMATE (
    IdClimate int NOT NULL,
    Description varchar(255)
  );
ALTER TABLE CLIMATE ADD CONSTRAINT CLIMATE_PK PRIMARY KEY ( IdClimate );

CREATE TABLE CLIMATE_MODIFIES_ATTRIBUTE (
    IdClimate int NOT NULL,
    IdAttribute int NOT NULL,
    Modifier smallint
  );
ALTER TABLE CLIMATE_MODIFIES_ATTRIBUTE ADD CONSTRAINT CLIMATE_MODIFIES_ATTRIBUTE_PK PRIMARY KEY ( IdClimate, IdAttribute );

CREATE TABLE CRAFTING_RECIPE (
    IdCraftingRecipe int NOT NULL,
    IdItem int NOT NULL,
    Count tinyint
  );
ALTER TABLE CRAFTING_RECIPE ADD CONSTRAINT CRAFTING_RECIPE_PK PRIMARY KEY ( IdCraftingRecipe );

CREATE TABLE CRAFTING_REQUIRES_RESSOURCE (
    IdCraftingRecipe int NOT NULL,
    IdRessource int NOT NULL,
    Count smallint
  );
ALTER TABLE CRAFTING_REQUIRES_RESSOURCE ADD CONSTRAINT CRAFTING_REQUIRES_RESSOURCE_PK PRIMARY KEY ( IdCraftingRecipe, IdRessource );

CREATE TABLE DICE_SET (
    IdDiceSet int NOT NULL,
    NumberOfDice tinyint
  );
ALTER TABLE DICE_SET ADD CONSTRAINT DICE_SET_PK PRIMARY KEY ( IdDiceSet );

CREATE TABLE DIE (
    IdDie int NOT NULL,
    IdDieType int NOT NULL,
    MIN tinyint,
    MAX tinyint,
    CanFail boolean
  );
ALTER TABLE DIE ADD CONSTRAINT DIE_PK PRIMARY KEY ( IdDie );

CREATE TABLE DIE_TYPE (
    IdDieType int NOT NULL,
    Name varchar(50)
  );
ALTER TABLE DIE_TYPE ADD CONSTRAINT DIE_TYPE_PK PRIMARY KEY ( IdDieType );

CREATE TABLE EQUIPMENT (
    IdEquipment int NOT NULL,
    EquipableSlot tinyint
  );
ALTER TABLE EQUIPMENT ADD CONSTRAINT EQUIPMENT_PK PRIMARY KEY ( IdEquipment );

CREATE TABLE EQUIPMENT_MODIFIES_ATTRIBUTE (
    IdEquipment int NOT NULL,
    IdAttribute int NOT NULL,
    Modifier smallint
  );
--  ERROR: PK name length exceeds maximum allowed length(30)
ALTER TABLE EQUIPMENT_MODIFIES_ATTRIBUTE ADD CONSTRAINT EQUIPMENT_MODIFIES_ATTRIBUTE_PK PRIMARY KEY ( IdEquipment, IdAttribute );

CREATE TABLE ITEM (
    IdItem int NOT NULL,
    Name varchar(50),
    Description varchar(256),
    Value int,
    Rank tinyint
  );
ALTER TABLE ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY ( IdItem );

CREATE TABLE MONSTER (
    IdMonster int NOT NULL,
    Boss boolean,
    Description varchar(255)
  );
ALTER TABLE MONSTER ADD CONSTRAINT MONSTER_PK PRIMARY KEY ( IdMonster );

CREATE TABLE MONSTER_CAN_DROP_ITEM (
    IdMonster int NOT NULL,
    IdItem int NOT NULL,
    Count smallint,
    Probability tinyint
  );
ALTER TABLE MONSTER_CAN_DROP_ITEM ADD CONSTRAINT MONSTER_CAN_DROP_ITEM_PK PRIMARY KEY ( IdMonster, IdItem );

CREATE TABLE PLAYER (
    IdPlayer int NOT NULL,
    Username varchar(50),
    Password varchar(255),
    Level smallint,
    Experience int,
    Money bigint
  );
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_PK PRIMARY KEY ( IdPlayer );

CREATE TABLE PLAYER_FINISH_QUEST (
    IdPlayer int NOT NULL,
    IdQuest int NOT NULL,
    DateCompletion timestamp
  );
ALTER TABLE PLAYER_FINISH_QUEST ADD CONSTRAINT PLAYER_FINISH_QUEST_PK PRIMARY KEY ( IdPlayer, IdQuest );

CREATE TABLE QUEST (
    IdQuest int NOT NULL,
    IdClimate int NOT NULL,
    Description clob
  );
ALTER TABLE QUEST ADD CONSTRAINT QUEST_PK PRIMARY KEY ( IdQuest );

CREATE TABLE QUEST_MADE_OF_ROOM (
    IdQuest int NOT NULL,
    IdRoom int NOT NULL,
    OrderNr tinyint
  );
ALTER TABLE QUEST_MADE_OF_ROOM ADD CONSTRAINT QUEST_MADE_OF_ROOM_PK PRIMARY KEY ( IdQuest, IdRoom );

CREATE TABLE QUEST_REWARDS_ITEM (
    IdQuest int NOT NULL,
    IdItem int NOT NULL,
    Count smallint
  );
ALTER TABLE QUEST_REWARDS_ITEM ADD CONSTRAINT QUEST_REWARDS_ITEM_PK PRIMARY KEY ( IdQuest, IdItem );

CREATE TABLE RESSOURCE (
    IdRessource int NOT NULL
  );
ALTER TABLE RESSOURCE ADD CONSTRAINT RESSOURCE_PK PRIMARY KEY ( IdRessource );

CREATE TABLE ROOM (
    IdRoom int NOT NULL
  );
ALTER TABLE ROOM ADD CONSTRAINT ROOM_PK PRIMARY KEY ( IdRoom );

CREATE TABLE ROOM_CONTAINS_MONSTER (
    IdRoom int NOT NULL,
    IdMonster int NOT NULL,
    Count tinyint
  );
ALTER TABLE ROOM_CONTAINS_MONSTER ADD CONSTRAINT ROOM_CONTAINS_MONSTER_PK PRIMARY KEY ( IdRoom, IdMonster );

-- Foreign keys
ALTER TABLE CHARACTER_EQUIPS_EQUIPMENT ADD CONSTRAINT CHARACTER_EQUIPS_EQUIPMENT_CHARACTER_FK FOREIGN KEY ( IdCharacter ) REFERENCES CHARACTER ( IdCharacter );
ALTER TABLE CHARACTER_EQUIPS_EQUIPMENT ADD CONSTRAINT CHARACTER_EQUIPS_EQUIPMENT_EQUIPMENT_FK FOREIGN KEY ( IdEquipment ) REFERENCES EQUIPMENT ( IdEquipment );
ALTER TABLE CHARACTER_HAS_ATTRIBUTE ADD CONSTRAINT CHARACTER_HAS_ATTRIBUTE_ATTRIBUTE_FK FOREIGN KEY ( IdAttribute ) REFERENCES ATTRIBUTE ( IdAttribute );
ALTER TABLE CHARACTER_HAS_ATTRIBUTE ADD CONSTRAINT CHARACTER_HAS_ATTRIBUTE_CHARACTER_FK FOREIGN KEY ( IdCharacter ) REFERENCES CHARACTER ( IdCharacter );
ALTER TABLE CHARACTER_HAS_ITEM ADD CONSTRAINT CHARACTER_HAS_ITEM_CHARACTER_FK FOREIGN KEY ( IdCharacter ) REFERENCES CHARACTER ( IdCharacter );
ALTER TABLE CHARACTER_HAS_ITEM ADD CONSTRAINT CHARACTER_HAS_ITEM_ITEM_FK FOREIGN KEY ( IdItem ) REFERENCES ITEM ( IdItem );
ALTER TABLE CHAR_EQUIPS_DIE_IN_DICE_SET ADD CONSTRAINT CHAR_EQUIPS_DIE_IN_DICE_SET_CHARACTER_FK FOREIGN KEY ( IdCharacter ) REFERENCES CHARACTER ( IdCharacter );
ALTER TABLE CHAR_EQUIPS_DIE_IN_DICE_SET ADD CONSTRAINT CHAR_EQUIPS_DIE_IN_DICE_SET_DICE_SET_FK FOREIGN KEY ( IdDiceSet ) REFERENCES DICE_SET ( IdDiceSet );
ALTER TABLE CHAR_EQUIPS_DIE_IN_DICE_SET ADD CONSTRAINT CHAR_EQUIPS_DIE_IN_DICE_SET_DIE_FK FOREIGN KEY ( IdDie ) REFERENCES DIE ( IdDie );
ALTER TABLE CLIMATE_MODIFIES_ATTRIBUTE ADD CONSTRAINT CLIMATE_MODIFIES_ATTRIBUTE_ATTRIBUTE_FK FOREIGN KEY ( IdAttribute ) REFERENCES ATTRIBUTE ( IdAttribute );
ALTER TABLE CLIMATE_MODIFIES_ATTRIBUTE ADD CONSTRAINT CLIMATE_MODIFIES_ATTRIBUTE_CLIMATE_FK FOREIGN KEY ( IdClimate ) REFERENCES CLIMATE ( IdClimate );
ALTER TABLE CRAFTING_RECIPE ADD CONSTRAINT CRAFTING_RECIPE_ITEM_FK FOREIGN KEY ( IdItem ) REFERENCES ITEM ( IdItem );
ALTER TABLE CRAFTING_REQUIRES_RESSOURCE ADD CONSTRAINT CRAFTING_REQUIRES_RESSOURCE_CRAFTING_RECIPE_FK FOREIGN KEY ( IdCraftingRecipe ) REFERENCES CRAFTING_RECIPE ( IdCraftingRecipe );
ALTER TABLE CRAFTING_REQUIRES_RESSOURCE ADD CONSTRAINT CRAFTING_REQUIRES_RESSOURCE_RESSOURCE_FK FOREIGN KEY ( IdRessource ) REFERENCES RESSOURCE ( IdRessource );
ALTER TABLE DICE_SET ADD CONSTRAINT DICE_SET_ITEM_FK FOREIGN KEY ( IdDiceSet ) REFERENCES ITEM ( IdItem );
ALTER TABLE DIE ADD CONSTRAINT DIE_DIE_TYPE_FK FOREIGN KEY ( IdDieType ) REFERENCES DIE_TYPE ( IdDieType );
ALTER TABLE DIE ADD CONSTRAINT DIE_ITEM_FK FOREIGN KEY ( IdDie ) REFERENCES ITEM ( IdItem );
ALTER TABLE EQUIPMENT ADD CONSTRAINT EQUIPMENT_ITEM_FK FOREIGN KEY ( IdEquipment ) REFERENCES ITEM ( IdItem );
ALTER TABLE EQUIPMENT_MODIFIES_ATTRIBUTE ADD CONSTRAINT EQUIPMENT_MODIFIES_ATTRIBUTE_ATTRIBUTE_FK FOREIGN KEY ( IdAttribute ) REFERENCES ATTRIBUTE ( IdAttribute );
ALTER TABLE EQUIPMENT_MODIFIES_ATTRIBUTE ADD CONSTRAINT EQUIPMENT_MODIFIES_ATTRIBUTE_EQUIPMENT_FK FOREIGN KEY ( IdEquipment ) REFERENCES EQUIPMENT ( IdEquipment );
ALTER TABLE MONSTER_CAN_DROP_ITEM ADD CONSTRAINT MONSTER_CAN_DROP_ITEM_ITEM_FK FOREIGN KEY ( IdItem ) REFERENCES ITEM ( IdItem );
ALTER TABLE MONSTER_CAN_DROP_ITEM ADD CONSTRAINT MONSTER_CAN_DROP_ITEM_MONSTER_FK FOREIGN KEY ( IdMonster ) REFERENCES MONSTER ( IdMonster );
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_CHARACTER_FK FOREIGN KEY ( IdPlayer ) REFERENCES CHARACTER ( IdCharacter );
ALTER TABLE PLAYER_FINISH_QUEST ADD CONSTRAINT PLAYER_FINISH_QUEST_PLAYER_FK FOREIGN KEY ( IdPlayer ) REFERENCES PLAYER ( IdPlayer );
ALTER TABLE PLAYER_FINISH_QUEST ADD CONSTRAINT PLAYER_FINISH_QUEST_QUEST_FK FOREIGN KEY ( IdQuest ) REFERENCES QUEST ( IdQuest );
ALTER TABLE QUEST ADD CONSTRAINT QUEST_CLIMATE_FK FOREIGN KEY ( IdClimate ) REFERENCES CLIMATE ( IdClimate );
ALTER TABLE QUEST_MADE_OF_ROOM ADD CONSTRAINT QUEST_MADE_OF_ROOM_QUEST_FK FOREIGN KEY ( IdQuest ) REFERENCES QUEST ( IdQuest );
ALTER TABLE QUEST_MADE_OF_ROOM ADD CONSTRAINT QUEST_MADE_OF_ROOM_ROOM_FK FOREIGN KEY ( IdRoom ) REFERENCES ROOM ( IdRoom );
ALTER TABLE QUEST_REWARDS_ITEM ADD CONSTRAINT QUEST_REWARDS_ITEM_ITEM_FK FOREIGN KEY ( IdItem ) REFERENCES ITEM ( IdItem );
ALTER TABLE QUEST_REWARDS_ITEM ADD CONSTRAINT QUEST_REWARDS_ITEM_QUEST_FK FOREIGN KEY ( IdQuest ) REFERENCES QUEST ( IdQuest );
ALTER TABLE RESSOURCE ADD CONSTRAINT RESSOURCE_ITEM_FK FOREIGN KEY ( IdRessource ) REFERENCES ITEM ( IdItem );
ALTER TABLE ROOM_CONTAINS_MONSTER ADD CONSTRAINT ROOM_CONTAINS_MONSTER_MONSTER_FK FOREIGN KEY ( IdMonster ) REFERENCES MONSTER ( IdMonster );
ALTER TABLE ROOM_CONTAINS_MONSTER ADD CONSTRAINT ROOM_CONTAINS_MONSTER_ROOM_FK FOREIGN KEY ( IdRoom ) REFERENCES ROOM ( IdRoom );
ALTER TABLE MONSTER ADD CONSTRAINT MONSTER_CHARACTER_FK FOREIGN KEY ( IdMonster ) REFERENCES CHARACTER ( IdCharacter );
